### ISSUE TITLE
Update TIGER polylines to 2020 Vintage

### ISSUE THREAD

**Issue by bransonf** [bransonf/Missouri_Pelias#1]
See https://github.com/pelias/interpolation/issues/263

Update pelias/interpolation to use the 2020 vintage

Official Census FTP server:
https://www2.census.gov/geo/tiger/TIGER2020/

See `/script/js/adapter/CensusFTP.js`, `/script/update_tiger.sh`
Additionally, non-essential instances in `tests` `dev` and `docs`

**Comment by missinglink** [comment]
Hi @bransonf I had a look at upgrading to 2021 today in https://github.com/pelias/interpolation/pull/274
There's a docker image listed in the comments which can be used for testing, please let me know if it works for you 🙇

**Comment by bransonf** [comment]
Amazing work @missinglink! 🙏 

I can confirm that the new image works seamlessly in the existing [pelias/docker](https://github.com/pelias/docker) workflow and I saw a modest improvement to coverage as compared to the 2016 data.
